language: go

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

before_install:
  - sudo apt-get update

before_script:
  - psql -c 'CREATE DATABASE musicexpress' -U postgres

script:
  - psql -c "SELECT version();"

#after_success:



