language: go

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc

#install:
#  - go get github.com/DATA-DOG/go-sqlmock v1.5.0
#	- go get github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973 // indirect
#	- go get github.com/gabriel-vasile/mimetype v1.1.2 // indirect
#	- go get github.com/go-playground/assert/v2 v2.0.1
#	- go get github.com/go-playground/validator/v10 v10.4.1
#	- go get github.com/golang/mock v1.4.4
#	- go get github.com/golang/protobuf v1.4.3
#	- go get github.com/jinzhu/copier v0.0.0-20201025035756-632e723a6687
#	- go get github.com/labstack/echo/v4 v4.1.17
#	- go get github.com/lib/pq v1.8.0
#	- go get github.com/lu4p/cat v0.1.5 // indirect
#	- go get github.com/mailru/easyjson v0.7.6
#	- go get github.com/matttproud/golang_protobuf_extensions v1.0.1 // indirect
#	- go get github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
#	- go get github.com/prometheus/client_golang v0.8.0
#	- go get github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e // indirect
#	- go get github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273 // indirect
#	- go get github.com/satori/go.uuid v1.2.0
#	- go get github.com/sirupsen/logrus v1.7.0
#	- go get github.com/stretchr/testify v1.6.1
#	- go get github.com/tcolgate/mp3 v0.0.0-20170426193717-e79c5a46d300
#	- go get golang.org/x/net v0.0.0-20201224014010-6772e930b67b
#	- go get golang.org/x/sys v0.0.0-20201223074533-0d417f636930 // indirect
#	- go get golang.org/x/text v0.3.4 // indirect
#	- go get golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
#	- go get google.golang.org/genproto v0.0.0-20201214200347-8c77b98c765d // indirect
#	- go get google.golang.org/grpc v1.34.0
#	- go get google.golang.org/protobuf v1.25.0
#	- go get gopkg.in/check.v1 v1.0.0-20200902074654-038fdea0a05b // indirect


before_script:
  - psql -c "SELECT version();"
  - psql -c "CREATE DATABASE musicexpress" -U postgres
  - psql -d musicexpress -f ./postgres/initDB.sql
  - psql -d musicexpress -c "SELECT * FROM artists"

script:
  # run tests
  #- go run app/track_microservice/main.go config.json
  #- go run app/session_microservice/main.go config.json
  #- go run app/main/main.go config.json
  
  - make tests

  - psql -c "DROP DATABASE musicexpress"




