language: go

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

before_install:
- cp .netrc ~/.netrc
- chmod 600 ~/.netrc

before_script:
  - psql -c "SELECT version();"
  - psql -c "CREATE DATABASE musicexpress" -U postgres
  - psql -d musicexpress -f ./postgres/initDB.sql
  - psql -d musicexpress -c "SELECT * FROM artists"

script:
  # run tests
  - make tests
  
  - psql -c "DROP DATABASE musicexpress"




