language: go

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

#before_install:
#  - sudo apt-get update

before_script:
  - psql -c "SELECT version();"
  - psql -c "CREATE DATABASE musicexpress" -U postgres
  - psql -d musicexpress -f ./postgres/initDB.sql

script:
  - psql -c "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name";
  - psql -c "DROP DATABASE musicexpress"

#after_success:



