language: go

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc

install:
  - github.com/DATA-DOG/go-sqlmock
	- github.com/beorn7/perks
	- github.com/gabriel-vasile/mimetype
	- github.com/go-playground/assert/v2
	- github.com/go-playground/validator/v10
	- github.com/golang/mock
	- github.com/golang/protobuf
	- github.com/jinzhu/copier
	- github.com/labstack/echo/v4
	- github.com/lib/pq
	- github.com/lu4p/cat
	- github.com/mailru/easyjson
	- github.com/matttproud/golang_protobuf_extensions
	- github.com/niemeyer/pretty
	- github.com/prometheus/client_golang
	- github.com/prometheus/common
	- github.com/prometheus/procfs
	- github.com/satori/go.uuid
	- github.com/sirupsen/logrus
	- github.com/stretchr/testify
	- github.com/tcolgate/mp3
	- golang.org/x/net
	- golang.org/x/sys 
	- golang.org/x/text
	- golang.org/x/xerrors 
	- google.golang.org/genproto
	- google.golang.org/grpc
	- google.golang.org/protobuf
	- gopkg.in/check.v1


before_script:
  - psql -c "SELECT version();"
  - psql -c "CREATE DATABASE musicexpress" -U postgres
  - psql -d musicexpress -f ./postgres/initDB.sql
  - psql -d musicexpress -c "SELECT * FROM artists"

script:
  # run tests
  #- go run app/track_microservice/main.go config.json
  #- go run app/session_microservice/main.go config.json
  #- go run app/main/main.go config.json
  
  - make tests

  - psql -c "DROP DATABASE musicexpress"




