language: go

go:
  - "1.15.2"

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc

before_script:
  # --------------------- Create test database ------------------
  - psql -c "SELECT version();"
  - psql -c "CREATE DATABASE musicexpress" -U postgres
  - psql -d musicexpress -f ./postgres/initDB.sql
  - psql -d musicexpress -c "SELECT * FROM artists"

script:
  # ---------------------- run tests -----------------------------
  
  # run microservices 
  - env GO111MODULE=on go run app/track_microservice/main.go config.json &
  - env GO111MODULE=on go run app/session_microservice/main.go config.json &
  - env GO111MODULE=on go run app/main/main.go config.json &
  - env GO111MODULE=on go run app/admin_microservice/main.go config.json & 

  - env GO111MODULE=on make tests

  # drop test database
  - psql -c "DROP DATABASE musicexpress"
