language: go

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

before_script:
  - psql -c "SELECT version();"
  - psql -c "CREATE DATABASE musicexpress" -U postgres
  - psql -d musicexpress -f ./postgres/initDB.sql

script:
  - psql -d musicexpress -c "SELECT * FROM artists"

  - make tests
  
  - psql -c "DROP DATABASE musicexpress"




