// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2020_2_CodeExpress/internal/user (interfaces: UserRep,UserUsecase)

// Package mock_user is a generated GoMock package.
package mock_user

import (
	models "github.com/go-park-mail-ru/2020_2_CodeExpress/internal/models"
	error_response "github.com/go-park-mail-ru/2020_2_CodeExpress/internal/tools/error_response"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserRep is a mock of UserRep interface
type MockUserRep struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepMockRecorder
}

// MockUserRepMockRecorder is the mock recorder for MockUserRep
type MockUserRepMockRecorder struct {
	mock *MockUserRep
}

// NewMockUserRep creates a new mock instance
func NewMockUserRep(ctrl *gomock.Controller) *MockUserRep {
	mock := &MockUserRep{ctrl: ctrl}
	mock.recorder = &MockUserRepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRep) EXPECT() *MockUserRepMockRecorder {
	return m.recorder
}

// Insert mocks base method
func (m *MockUserRep) Insert(arg0, arg1, arg2 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockUserRepMockRecorder) Insert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUserRep)(nil).Insert), arg0, arg1, arg2)
}

// InsertSubscription mocks base method
func (m *MockUserRep) InsertSubscription(arg0 uint64, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSubscription", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSubscription indicates an expected call of InsertSubscription
func (mr *MockUserRepMockRecorder) InsertSubscription(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSubscription", reflect.TypeOf((*MockUserRep)(nil).InsertSubscription), arg0, arg1)
}

// RemoveSubscription mocks base method
func (m *MockUserRep) RemoveSubscription(arg0 uint64, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscription", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubscription indicates an expected call of RemoveSubscription
func (mr *MockUserRepMockRecorder) RemoveSubscription(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscription", reflect.TypeOf((*MockUserRep)(nil).RemoveSubscription), arg0, arg1)
}

// SelectById mocks base method
func (m *MockUserRep) SelectById(arg0 uint64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectById", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectById indicates an expected call of SelectById
func (mr *MockUserRepMockRecorder) SelectById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectById", reflect.TypeOf((*MockUserRep)(nil).SelectById), arg0)
}

// SelectByLogin mocks base method
func (m *MockUserRep) SelectByLogin(arg0 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByLogin", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByLogin indicates an expected call of SelectByLogin
func (mr *MockUserRepMockRecorder) SelectByLogin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByLogin", reflect.TypeOf((*MockUserRep)(nil).SelectByLogin), arg0)
}

// SelectByName mocks base method
func (m *MockUserRep) SelectByName(arg0 string, arg1 uint64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByName", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByName indicates an expected call of SelectByName
func (mr *MockUserRepMockRecorder) SelectByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByName", reflect.TypeOf((*MockUserRep)(nil).SelectByName), arg0, arg1)
}

// SelectByNameOrEmail mocks base method
func (m *MockUserRep) SelectByNameOrEmail(arg0, arg1 string) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByNameOrEmail", arg0, arg1)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByNameOrEmail indicates an expected call of SelectByNameOrEmail
func (mr *MockUserRepMockRecorder) SelectByNameOrEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByNameOrEmail", reflect.TypeOf((*MockUserRep)(nil).SelectByNameOrEmail), arg0, arg1)
}

// SelectIfAdmin mocks base method
func (m *MockUserRep) SelectIfAdmin(arg0 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectIfAdmin", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectIfAdmin indicates an expected call of SelectIfAdmin
func (mr *MockUserRepMockRecorder) SelectIfAdmin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectIfAdmin", reflect.TypeOf((*MockUserRep)(nil).SelectIfAdmin), arg0)
}

// SelectSubscriptions mocks base method
func (m *MockUserRep) SelectSubscriptions(arg0, arg1 uint64) (*models.Subscriptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSubscriptions", arg0, arg1)
	ret0, _ := ret[0].(*models.Subscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectSubscriptions indicates an expected call of SelectSubscriptions
func (mr *MockUserRepMockRecorder) SelectSubscriptions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSubscriptions", reflect.TypeOf((*MockUserRep)(nil).SelectSubscriptions), arg0, arg1)
}

// Update mocks base method
func (m *MockUserRep) Update(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUserRepMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRep)(nil).Update), arg0)
}

// MockUserUsecase is a mock of UserUsecase interface
type MockUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseMockRecorder
}

// MockUserUsecaseMockRecorder is the mock recorder for MockUserUsecase
type MockUserUsecaseMockRecorder struct {
	mock *MockUserUsecase
}

// NewMockUserUsecase creates a new mock instance
func NewMockUserUsecase(ctrl *gomock.Controller) *MockUserUsecase {
	mock := &MockUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserUsecase) EXPECT() *MockUserUsecaseMockRecorder {
	return m.recorder
}

// AddSubscription mocks base method
func (m *MockUserUsecase) AddSubscription(arg0 uint64, arg1 string) *error_response.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubscription", arg0, arg1)
	ret0, _ := ret[0].(*error_response.ErrorResponse)
	return ret0
}

// AddSubscription indicates an expected call of AddSubscription
func (mr *MockUserUsecaseMockRecorder) AddSubscription(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubscription", reflect.TypeOf((*MockUserUsecase)(nil).AddSubscription), arg0, arg1)
}

// CheckAdmin mocks base method
func (m *MockUserUsecase) CheckAdmin(arg0 uint64) (bool, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdmin", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// CheckAdmin indicates an expected call of CheckAdmin
func (mr *MockUserUsecaseMockRecorder) CheckAdmin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdmin", reflect.TypeOf((*MockUserUsecase)(nil).CheckAdmin), arg0)
}

// Create mocks base method
func (m *MockUserUsecase) Create(arg0, arg1, arg2 string) (*models.User, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockUserUsecaseMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserUsecase)(nil).Create), arg0, arg1, arg2)
}

// GetById mocks base method
func (m *MockUserUsecase) GetById(arg0 uint64) (*models.User, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// GetById indicates an expected call of GetById
func (mr *MockUserUsecaseMockRecorder) GetById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserUsecase)(nil).GetById), arg0)
}

// GetByName mocks base method
func (m *MockUserUsecase) GetByName(arg0 string, arg1 uint64) (*models.User, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName
func (mr *MockUserUsecaseMockRecorder) GetByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockUserUsecase)(nil).GetByName), arg0, arg1)
}

// GetSubscriptions mocks base method
func (m *MockUserUsecase) GetSubscriptions(arg0, arg1 uint64) (*models.Subscriptions, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptions", arg0, arg1)
	ret0, _ := ret[0].(*models.Subscriptions)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// GetSubscriptions indicates an expected call of GetSubscriptions
func (mr *MockUserUsecaseMockRecorder) GetSubscriptions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptions", reflect.TypeOf((*MockUserUsecase)(nil).GetSubscriptions), arg0, arg1)
}

// GetUserByLogin mocks base method
func (m *MockUserUsecase) GetUserByLogin(arg0, arg1 string) (*models.User, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin
func (mr *MockUserUsecaseMockRecorder) GetUserByLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUserUsecase)(nil).GetUserByLogin), arg0, arg1)
}

// RemoveSubscription mocks base method
func (m *MockUserUsecase) RemoveSubscription(arg0 uint64, arg1 string) *error_response.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscription", arg0, arg1)
	ret0, _ := ret[0].(*error_response.ErrorResponse)
	return ret0
}

// RemoveSubscription indicates an expected call of RemoveSubscription
func (mr *MockUserUsecaseMockRecorder) RemoveSubscription(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscription", reflect.TypeOf((*MockUserUsecase)(nil).RemoveSubscription), arg0, arg1)
}

// UpdateAvatar mocks base method
func (m *MockUserUsecase) UpdateAvatar(arg0 uint64, arg1 string) (*models.User, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// UpdateAvatar indicates an expected call of UpdateAvatar
func (mr *MockUserUsecaseMockRecorder) UpdateAvatar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockUserUsecase)(nil).UpdateAvatar), arg0, arg1)
}

// UpdatePassword mocks base method
func (m *MockUserUsecase) UpdatePassword(arg0 uint64, arg1, arg2 string) *error_response.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(*error_response.ErrorResponse)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword
func (mr *MockUserUsecaseMockRecorder) UpdatePassword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserUsecase)(nil).UpdatePassword), arg0, arg1, arg2)
}

// UpdateProfile mocks base method
func (m *MockUserUsecase) UpdateProfile(arg0 uint64, arg1, arg2 string) (*models.User, *error_response.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error_response.ErrorResponse)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile
func (mr *MockUserUsecaseMockRecorder) UpdateProfile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserUsecase)(nil).UpdateProfile), arg0, arg1, arg2)
}
